package:
  name: enaml-native-icons
  version: 1.0.0

requirements:
  run:
    - enaml-native

build:
  number: 1
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native-icons
  license: MIT