package:
  name: enaml-native-icons
  version: 2.0.1

requirements:
  run:
    - enaml-native

build:
  number: 0
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native-icons
  summary: "Icons for enaml-native"
  license: MIT